CC=gcc
CFLAGS=-O0 -g -Wall -I/usr/include -I/usr/X11R6/include `pkg-config --cflags glib-2.0 gconf-2.0 gthread-2.0 hildon-1`
LDFLAGS=-pthread -L/usr/X11R6/lib -lm `pkg-config --libs glib-2.0 gthread-2.0 hildon-1`

EXAMPLES = $(patsubst %.c,%,$(wildcard *.c))

all: $(EXAMPLES)


%:%.c
	gcc $(LDFLAGS) $(CFLAGS) -o $@ $<


clean:
	rm -f *example
	rm -f *example-[1-9]

